#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_navset_event_handler

#include "Basic.hpp"

#include "EEscapeBehaviour_structs.hpp"


namespace SDK::Params
{

}

