#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_save_manager

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_save_manager.BP_save_manager_C.ExecuteLoadingFromSaveID
// 0x0010 (0x0010 - 0x0000)
struct BP_save_manager_C_ExecuteLoadingFromSaveID final
{
public:
	class FString                                 SaveID;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_save_manager_C_ExecuteLoadingFromSaveID;

}

