#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_TabButtons

#include "Basic.hpp"


namespace SDK::Params
{

// Function BPI_TabButtons.BPI_TabButtons_C.SetSelected
// 0x0001 (0x0001 - 0x0000)
struct BPI_TabButtons_C_SetSelected final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_TabButtons_C_SetSelected;

// Function BPI_TabButtons.BPI_TabButtons_C.GetSelected
// 0x0001 (0x0001 - 0x0000)
struct BPI_TabButtons_C_GetSelected final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_TabButtons_C_GetSelected;

}

