#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EEscapeBehaviour

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EEscapeBehaviour.EEscapeBehaviour
// NumValues: 0x0003
enum class EEscapeBehaviour : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator0                           = 1,
	EEscapeBehaviour_MAX                     = 2,
};

}

