#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_Temperature

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_Temperature.Enum_Temperature
// NumValues: 0x0008
enum class Enum_Temperature : uint8
{
	NewEnumerator7                           = 0,
	NewEnumerator8                           = 1,
	NewEnumerator9                           = 2,
	NewEnumerator10                          = 3,
	NewEnumerator11                          = 4,
	NewEnumerator12                          = 5,
	NewEnumerator13                          = 6,
	Enum_MAX                                 = 7,
};

}

