#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_GrowthStage

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_GrowthStage.Enum_GrowthStage
// NumValues: 0x0006
enum class Enum_GrowthStage : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator3                           = 2,
	NewEnumerator4                           = 3,
	NewEnumerator5                           = 4,
	Enum_MAX                                 = 5,
};

}

