#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EShortcutKeyType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EShortcutKeyType.EShortcutKeyType
// NumValues: 0x0004
enum class EShortcutKeyType : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator1                           = 2,
	EShortcutKeyType_MAX                     = 3,
};

}

