#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SettingItemWhiteDots

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_SettingItemWhiteDots.WBP_SettingItemWhiteDots_C.SetOpacity
// 0x0008 (0x0008 - 0x0000)
struct WBP_SettingItemWhiteDots_C_SetOpacity final
{
public:
	float                                         Opacity;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FClamp_ReturnValue;                       // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_SettingItemWhiteDots_C_SetOpacity;

}

