#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NavbarOverlay

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function WBP_NavbarOverlay.WBP_NavbarOverlay_C.SetNavbarVisibility
// 0x0001 (0x0001 - 0x0000)
struct WBP_NavbarOverlay_C_SetNavbarVisibility final
{
public:
	ESlateVisibility                              InVisibility;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_NavbarOverlay_C_SetNavbarVisibility;

}

